### PR TITLE
Add package.json and fix .gitmodules

### PR DESCRIPTION
**Pull request by i8ramin**
I added a package.json file and fixed the submodule urls.

### CODE REVIEW

**Comment by martin-naumann** [comment]
:+1: for this PR. If that is merged, I will close my PR #216

**Comment by soyjavi** [comment]
It's fixed :)

**Comment by martin-naumann** [comment]
How (or where) is that fixed? I don't see a package.json in the master here :(

**Comment by soyjavi** [comment]
https://github.com/tapquo/Lungo.js/blob/master/.gitmodules

**Comment by martin-naumann** [comment]
Well, but that was only half of the dail.
For me the real deal is the package.json, but for that matter, there is #216

On Thu, Jun 13, 2013 at 11:54 AM, Javi Jiménez notifications@github.comwrote:

> https://github.com/tapquo/Lungo.js/blob/master/.gitmodules
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tapquo/Lungo.js/pull/213#issuecomment-19382285
> .

## 

Martin Naumann | Technology Expert R&D | Centralway Incubator

**Pull request closed without merging**
