### PR TITLE
coffee version of Storage to have cache() working again

### PR DESCRIPTION
**Pull request by fix**
done coffee version to have caching services working again. Not put the glue inside the main coffee file so it is safe.

### CODE REVIEW

**Comment by soyjavi** [comment]
Better if you use Device.js (storage)

**Comment by fix** [comment]
So I guess the cache manager in Lungo should be upgraded to device (guess this is this one https://github.com/soyjavi/device.js)

Any device.js to download somewhere ?

**Comment by fix** [comment]
found the way to do it !

```
Lungo.Data.Storage = (function(){
    return {
        persistent:Device.Storage.local,
        session:Device.Storage.session
    };
 })();
```

**Comment by soyjavi** [comment]
https://github.com/soyjavi/package-device.js

**Comment by fix** [comment]
Should i submit a patch with dependency to device.js and the code to wire device.js to Lungo.Data.Storage? Or do you plan something else?

**Comment by soyjavi** [comment]
I'm sorry but I can't accept you pullrequest, Lungo not have to be coupled to DATA, it depends on the business application.

**Comment by fix** [comment]
ok then remove the cache from the API, since it is coupled to DATA....

**Pull request closed without merging**
