### PR TITLE
Fix for rewinding history too far.

### PR DESCRIPTION
**Pull request by mark-bradshaw**
Make sure that history.removeLast can't go back too far.  This is a painless error check, and has actually happened to me in the wild by accident.

### CODE REVIEW

**Comment by martin-naumann** [comment]
Just being curious: Why not _history.pop()?

**Comment by mark-bradshaw** [comment]
Probably because my brain wasn't really in, "let's make it really right" mode, and was more in "make that error go away" mode.  Pop would be fine.  I just want it to go away.

**Comment by martin-naumann** [comment]
Ah okay, no worries, I know those moments.
I just stumbled upon this on jsPerf: http://jsperf.com/pop-vs-shift-on-a-array/6
Which says, that in most cases decreasing length is slower than pop(), or it's equally fast sometimes. :rabbit:

**Comment by mark-bradshaw** [comment]
Makes sense to me.

**Pull request closed without merging**
