### PR TITLE
Setting the size on all images used within a .list makes it really hard ...

### PR DESCRIPTION
**Pull request by abossard**
...to use images in .list.

I think a more concise solution would be to add .icon class to images, that are used as icons.

### CODE REVIEW

**Comment by soyjavi** [comment]
You must overwrite your own style... no the master class.

**Comment by abossard** [comment]
Thanks for your reply! I'm a huge fan of Lungo.js! Great work!

I know what you mean, but I think in this case, its better if the master would not set the size on any images in a .list in the first place. 
- the css code is about styling the .icon that can occur in a .list
- icons are already sufficiently classified by the .icon class
- why should there be a default for all img tags within .list?

These are the reasons why I think it should be changed.

**Comment by soyjavi** [comment]
Thanks for your support :)

Anyway the sizes are assigned for data-icon or data-image attributes. If your list item is not the common design you will to override the masterclass via ooCSS.

**Comment by abossard** [comment]
ok, thanks!

**Pull request closed without merging**
