### PR TITLE
Issue 71

### PR DESCRIPTION
**Pull request by amuino**
Fix for #71

Added a new method to the router to "rewind" to a previous section.

### CODE REVIEW

**Comment by soyjavi** [comment]
In version 1.2 will be a new improved router, I will implement your code in the.

Thank you.

**Comment by jcalonso** [comment]
Found this bug too.

Waiting for the 1.2 :D

**Comment by soyjavi** [comment]
Release 1.2 is up!!!!

**Comment by k33g** [comment]
Hello.
Can you explain how to use it please, because i've the same issue with 1.2 version.
Thank you

**Comment by amuino** [comment]
I can't find my `rewind` method (from the pull request) in the newest https://github.com/TapQuo/Lungo.js/blob/master/src/router/Lungo.Router.js or https://github.com/TapQuo/Lungo.js/blob/master/src/boot/Lungo.Boot.Events.js

Has it been merged in a different way?

**Pull request closed without merging**
